/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odyssey.ui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.plaf.ColorUIResource;
import odyssey.CustomPlayer;
import odyssey.Metodos;

/**
 *
 * @author jaam
 */
public class EqFrame extends javax.swing.JFrame {

    private boolean SeHizoClic=false;
    private final Component parent;
    
    public EqFrame(Component p) {
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(EqFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        //this.setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        Escuchadores();
        UbicarSlider();
        jComboBox1.setSelectedIndex(CustomPlayer.ItemEc);
        this.setLocationRelativeTo(null);
        parent=p;
        bloquearParent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSlider11 = new javax.swing.JSlider();
        jComboBox1 = new javax.swing.JComboBox();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSlider5 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jSlider6 = new javax.swing.JSlider();
        jSlider7 = new javax.swing.JSlider();
        jSlider8 = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSlider9 = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSlider10 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Equalizer");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(java.awt.Color.black);

        jSlider11.setBackground(new java.awt.Color(0, 0, 0));
        jSlider11.setForeground(new java.awt.Color(51, 153, 255));
        jSlider11.setMajorTickSpacing(2);
        jSlider11.setMaximum(14);
        jSlider11.setMinimum(-14);
        jSlider11.setPaintTicks(true);
        jSlider11.setToolTipText("Balance");
        jSlider11.setValue(0);
        jSlider11.setFocusable(false);
        jSlider11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider11StateChanged(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Rock", "Rap", "Grunge", "Metal", "Dance", "Tecno", "Country", "Jazz", "Acústica", "Fol", "New Age", "Clásica", "Blues", "Clásicos", "Reggae", "Opera", "Swing", "Personalizado" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
        });

        jSlider1.setBackground(new java.awt.Color(0, 0, 0));
        jSlider1.setForeground(new java.awt.Color(51, 153, 255));
        jSlider1.setMajorTickSpacing(2);
        jSlider1.setMaximum(14);
        jSlider1.setMinimum(-14);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        jSlider1.setFocusable(false);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jSlider2.setBackground(new java.awt.Color(0, 0, 0));
        jSlider2.setForeground(new java.awt.Color(51, 153, 255));
        jSlider2.setMajorTickSpacing(2);
        jSlider2.setMaximum(14);
        jSlider2.setMinimum(-14);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(0);
        jSlider2.setFocusable(false);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        jSlider3.setBackground(new java.awt.Color(0, 0, 0));
        jSlider3.setForeground(new java.awt.Color(51, 153, 255));
        jSlider3.setMajorTickSpacing(2);
        jSlider3.setMaximum(14);
        jSlider3.setMinimum(-14);
        jSlider3.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider3.setPaintTicks(true);
        jSlider3.setValue(0);
        jSlider3.setFocusable(false);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });

        jSlider4.setBackground(new java.awt.Color(0, 0, 0));
        jSlider4.setForeground(new java.awt.Color(51, 153, 255));
        jSlider4.setMajorTickSpacing(2);
        jSlider4.setMaximum(14);
        jSlider4.setMinimum(-14);
        jSlider4.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider4.setPaintTicks(true);
        jSlider4.setValue(0);
        jSlider4.setFocusable(false);
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4StateChanged(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("31");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("62");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("125");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("250");

        jSlider5.setBackground(new java.awt.Color(0, 0, 0));
        jSlider5.setForeground(new java.awt.Color(51, 153, 255));
        jSlider5.setMajorTickSpacing(2);
        jSlider5.setMaximum(14);
        jSlider5.setMinimum(-14);
        jSlider5.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider5.setPaintTicks(true);
        jSlider5.setValue(0);
        jSlider5.setFocusable(false);
        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider5StateChanged(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("500");

        jSlider6.setBackground(new java.awt.Color(0, 0, 0));
        jSlider6.setForeground(new java.awt.Color(51, 153, 255));
        jSlider6.setMajorTickSpacing(2);
        jSlider6.setMaximum(14);
        jSlider6.setMinimum(-14);
        jSlider6.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider6.setPaintTicks(true);
        jSlider6.setValue(0);
        jSlider6.setFocusable(false);
        jSlider6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider6StateChanged(evt);
            }
        });

        jSlider7.setBackground(new java.awt.Color(0, 0, 0));
        jSlider7.setForeground(new java.awt.Color(51, 153, 255));
        jSlider7.setMajorTickSpacing(2);
        jSlider7.setMaximum(14);
        jSlider7.setMinimum(-14);
        jSlider7.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider7.setPaintTicks(true);
        jSlider7.setValue(0);
        jSlider7.setFocusable(false);
        jSlider7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider7StateChanged(evt);
            }
        });

        jSlider8.setBackground(new java.awt.Color(0, 0, 0));
        jSlider8.setForeground(new java.awt.Color(51, 153, 255));
        jSlider8.setMajorTickSpacing(2);
        jSlider8.setMaximum(14);
        jSlider8.setMinimum(-14);
        jSlider8.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider8.setPaintTicks(true);
        jSlider8.setValue(0);
        jSlider8.setFocusable(false);
        jSlider8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider8StateChanged(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("1k");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("2k");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("4k");

        jSlider9.setBackground(new java.awt.Color(0, 0, 0));
        jSlider9.setForeground(new java.awt.Color(51, 153, 255));
        jSlider9.setMajorTickSpacing(2);
        jSlider9.setMaximum(14);
        jSlider9.setMinimum(-14);
        jSlider9.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider9.setPaintTicks(true);
        jSlider9.setValue(0);
        jSlider9.setFocusable(false);
        jSlider9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider9StateChanged(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("8k");

        jButton1.setText("Default");
        Border border = BorderFactory.createBevelBorder(BevelBorder.RAISED);
        UIManager.put("ToolTip.border", border);//coloca el tipo de borde
        UIManager.put("ToolTip.foreground", new ColorUIResource(Color.white));// color de las letras
        UIManager.put("ToolTip.background", new ColorUIResource(Color.black));//color de fondo
        jButton1.setToolTipText("Restablecer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });

        jSlider10.setBackground(new java.awt.Color(0, 0, 0));
        jSlider10.setForeground(new java.awt.Color(51, 153, 255));
        jSlider10.setMajorTickSpacing(2);
        jSlider10.setMaximum(14);
        jSlider10.setMinimum(-14);
        jSlider10.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider10.setPaintTicks(true);
        jSlider10.setValue(0);
        jSlider10.setFocusable(false);
        jSlider10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider10StateChanged(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("16k");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10))
                            .addComponent(jSlider10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSlider9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        desbloquearParent();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        GuardarInformacion();
    }//GEN-LAST:event_formWindowClosed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        char tecla=evt.getKeyChar();
        if(tecla==KeyEvent.VK_ESCAPE){
            desbloquearParent(); this.dispose();
        }
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Restablecer();
        jSlider11.setValue(0);
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSlider11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider11StateChanged
        CustomPlayer.Balance=(float)jSlider11.getValue()/jSlider11.getMaximum();
        OdysseyFrame.CambioEnEcualizador=true;
    }//GEN-LAST:event_jSlider11StateChanged

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased
        char tecla=evt.getKeyChar();
        if(tecla==KeyEvent.VK_ESCAPE){
            desbloquearParent(); this.dispose();
        }
    }//GEN-LAST:event_jComboBox1KeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        CustomPlayer.ItemEc=jComboBox1.getSelectedIndex();
        if(jComboBox1.getSelectedIndex()==0){
            Restablecer();
        }else if(jComboBox1.getSelectedIndex()==1){
            jSlider1.setValue(-1); jSlider6.setValue(-1);
            jSlider2.setValue(1); jSlider7.setValue(0);
            jSlider3.setValue(2); jSlider8.setValue(0);
            jSlider4.setValue(3); jSlider9.setValue(4);
            jSlider5.setValue(-1); jSlider10.setValue(4);
        }else if(jComboBox1.getSelectedIndex()==2){
            jSlider1.setValue(-1); jSlider6.setValue(-1);
            jSlider2.setValue(0); jSlider7.setValue(0);
            jSlider3.setValue(2); jSlider8.setValue(0);
            jSlider4.setValue(2); jSlider9.setValue(4);
            jSlider5.setValue(-1); jSlider10.setValue(6);
        }else if(jComboBox1.getSelectedIndex()==3){
            jSlider1.setValue(-4); jSlider6.setValue(0);
            jSlider2.setValue(0); jSlider7.setValue(2);
            jSlider3.setValue(0); jSlider8.setValue(3);
            jSlider4.setValue(-2); jSlider9.setValue(0);
            jSlider5.setValue(0); jSlider10.setValue(-3);
        }else if(jComboBox1.getSelectedIndex()==4){
            jSlider1.setValue(-4); jSlider6.setValue(0);
            jSlider2.setValue(0); jSlider7.setValue(3);
            jSlider3.setValue(0); jSlider8.setValue(0);
            jSlider4.setValue(0); jSlider9.setValue(3);
            jSlider5.setValue(0); jSlider10.setValue(1);
        }else if(jComboBox1.getSelectedIndex()==5){
            jSlider1.setValue(-1); jSlider6.setValue(-1);
            jSlider2.setValue(4); jSlider7.setValue(0);
            jSlider3.setValue(5); jSlider8.setValue(0);
            jSlider4.setValue(1); jSlider9.setValue(4);
            jSlider5.setValue(-1); jSlider10.setValue(4);
        }else if(jComboBox1.getSelectedIndex()==6){
            jSlider1.setValue(-6); jSlider6.setValue(-2);
            jSlider2.setValue(1); jSlider7.setValue(0);
            jSlider3.setValue(4); jSlider8.setValue(0);
            jSlider4.setValue(-1); jSlider9.setValue(5);
            jSlider5.setValue(-1); jSlider10.setValue(5);
        }else if(jComboBox1.getSelectedIndex()==7){
            jSlider1.setValue(-1); jSlider6.setValue(0);
            jSlider2.setValue(0); jSlider7.setValue(0);
            jSlider3.setValue(0); jSlider8.setValue(0);
            jSlider4.setValue(2); jSlider9.setValue(3);
            jSlider5.setValue(2); jSlider10.setValue(3);
        }else if(jComboBox1.getSelectedIndex()==8){
            jSlider1.setValue(0); jSlider6.setValue(3);
            jSlider2.setValue(0); jSlider7.setValue(0);
            jSlider3.setValue(0); jSlider8.setValue(2);
            jSlider4.setValue(3); jSlider9.setValue(4);
            jSlider5.setValue(3); jSlider10.setValue(4);
        }else if(jComboBox1.getSelectedIndex()==9){
            jSlider1.setValue(0); jSlider6.setValue(0);
            jSlider2.setValue(1); jSlider7.setValue(0);
            jSlider3.setValue(2); jSlider8.setValue(0);
            jSlider4.setValue(0); jSlider9.setValue(2);
            jSlider5.setValue(0); jSlider10.setValue(2);
        }else if(jComboBox1.getSelectedIndex()==10){
            jSlider1.setValue(-1); jSlider6.setValue(0);
            jSlider2.setValue(0); jSlider7.setValue(0);
            jSlider3.setValue(1); jSlider8.setValue(0);
            jSlider4.setValue(0); jSlider9.setValue(2);
            jSlider5.setValue(2); jSlider10.setValue(0);
        }else if(jComboBox1.getSelectedIndex()==11){
            jSlider1.setValue(0); jSlider6.setValue(0);
            jSlider2.setValue(3); jSlider7.setValue(0);
            jSlider3.setValue(3); jSlider8.setValue(0);
            jSlider4.setValue(0); jSlider9.setValue(1);
            jSlider5.setValue(0); jSlider10.setValue(1);
        }else if(jComboBox1.getSelectedIndex()==12){
            jSlider1.setValue(0); jSlider6.setValue(0);
            jSlider2.setValue(6); jSlider7.setValue(0);
            jSlider3.setValue(6); jSlider8.setValue(0);
            jSlider4.setValue(3); jSlider9.setValue(2);
            jSlider5.setValue(0); jSlider10.setValue(2);
        }else if(jComboBox1.getSelectedIndex()==13){
            jSlider1.setValue(-1); jSlider6.setValue(0);
            jSlider2.setValue(0); jSlider7.setValue(0);
            jSlider3.setValue(2); jSlider8.setValue(0);
            jSlider4.setValue(1); jSlider9.setValue(-1);
            jSlider5.setValue(0); jSlider10.setValue(-3);
        }else if(jComboBox1.getSelectedIndex()==14){
            jSlider1.setValue(-2); jSlider6.setValue(0);
            jSlider2.setValue(0); jSlider7.setValue(0);
            jSlider3.setValue(2); jSlider8.setValue(0);
            jSlider4.setValue(1); jSlider9.setValue(-2);
            jSlider5.setValue(0); jSlider10.setValue(-5);
        }else if(jComboBox1.getSelectedIndex()==15){
            jSlider1.setValue(-1); jSlider6.setValue(3);
            jSlider2.setValue(0); jSlider7.setValue(4);
            jSlider3.setValue(0); jSlider8.setValue(0);
            jSlider4.setValue(-3); jSlider9.setValue(3);
            jSlider5.setValue(0); jSlider10.setValue(4);
        }else if(jComboBox1.getSelectedIndex()==16){
            jSlider1.setValue(0); jSlider6.setValue(2);
            jSlider2.setValue(0); jSlider7.setValue(5);
            jSlider3.setValue(0); jSlider8.setValue(2);
            jSlider4.setValue(3); jSlider9.setValue(0);
            jSlider5.setValue(4); jSlider10.setValue(0);
        }else if(jComboBox1.getSelectedIndex()==17){
            jSlider1.setValue(-1); jSlider6.setValue(3);
            jSlider2.setValue(0); jSlider7.setValue(0);
            jSlider3.setValue(0); jSlider8.setValue(2);
            jSlider4.setValue(0); jSlider9.setValue(4);
            jSlider5.setValue(3); jSlider10.setValue(4);
        }else if(jComboBox1.getSelectedIndex()==18){
            if(!SeHizoClic){
                jSlider1.setValue(CustomPlayer.EqP[0]); jSlider6.setValue(CustomPlayer.EqP[5]);
                jSlider2.setValue(CustomPlayer.EqP[1]); jSlider7.setValue(CustomPlayer.EqP[6]);
                jSlider3.setValue(CustomPlayer.EqP[2]); jSlider8.setValue(CustomPlayer.EqP[7]);
                jSlider4.setValue(CustomPlayer.EqP[3]); jSlider9.setValue(CustomPlayer.EqP[8]);
                jSlider5.setValue(CustomPlayer.EqP[4]); jSlider10.setValue(CustomPlayer.EqP[9]);
            } SeHizoClic=false;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jSlider10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider10StateChanged
        CustomPlayer.Eq[9]=(float)jSlider10.getValue()/jSlider10.getMaximum();
        OdysseyFrame.CambioEnEcualizador=true;
    }//GEN-LAST:event_jSlider10StateChanged

    private void jSlider9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider9StateChanged
        CustomPlayer.Eq[8]=(float)jSlider9.getValue()/jSlider9.getMaximum();
        OdysseyFrame.CambioEnEcualizador=true;
    }//GEN-LAST:event_jSlider9StateChanged

    private void jSlider8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider8StateChanged
        CustomPlayer.Eq[7]=(float)jSlider8.getValue()/jSlider8.getMaximum();
        OdysseyFrame.CambioEnEcualizador=true;
    }//GEN-LAST:event_jSlider8StateChanged

    private void jSlider7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider7StateChanged
        CustomPlayer.Eq[6]=(float)jSlider7.getValue()/jSlider7.getMaximum();
        OdysseyFrame.CambioEnEcualizador=true;
    }//GEN-LAST:event_jSlider7StateChanged

    private void jSlider6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider6StateChanged
        CustomPlayer.Eq[5]=(float)jSlider6.getValue()/jSlider6.getMaximum();
        OdysseyFrame.CambioEnEcualizador=true;
    }//GEN-LAST:event_jSlider6StateChanged

    private void jSlider5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider5StateChanged
        CustomPlayer.Eq[4]=(float)jSlider5.getValue()/jSlider5.getMaximum();
        OdysseyFrame.CambioEnEcualizador=true;
    }//GEN-LAST:event_jSlider5StateChanged

    private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4StateChanged
        CustomPlayer.Eq[3]=(float)jSlider4.getValue()/jSlider4.getMaximum();
        OdysseyFrame.CambioEnEcualizador=true;
    }//GEN-LAST:event_jSlider4StateChanged

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
        CustomPlayer.Eq[2]=(float)jSlider3.getValue()/jSlider3.getMaximum();
        OdysseyFrame.CambioEnEcualizador=true;
    }//GEN-LAST:event_jSlider3StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        CustomPlayer.Eq[1]=(float)jSlider2.getValue()/jSlider2.getMaximum();
        OdysseyFrame.CambioEnEcualizador=true;
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        CustomPlayer.Eq[0]=(float)jSlider1.getValue()/jSlider1.getMaximum();
        OdysseyFrame.CambioEnEcualizador=true;
    }//GEN-LAST:event_jSlider1StateChanged

    private void Escuchadores(){
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderMouseReleased(evt);
            }
        });
        jSlider2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderMouseReleased(evt);
            }
        });
        jSlider3.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderMouseReleased(evt);
            }
        });
        jSlider4.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderMouseReleased(evt);
            }
        });
        jSlider5.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderMouseReleased(evt);
            }
        });
        jSlider6.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderMouseReleased(evt);
            }
        });
        jSlider7.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderMouseReleased(evt);
            }
        });
        jSlider8.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderMouseReleased(evt);
            }
        });
        jSlider9.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderMouseReleased(evt);
            }
        });
        jSlider10.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderMouseReleased(evt);
            }
        });
    }
    
    private void jSliderMouseReleased(java.awt.event.MouseEvent evt) {                                      
       if(jComboBox1.getSelectedIndex()!=18){
           SeHizoClic=true; 
           jComboBox1.setSelectedIndex(18);
       }
        CustomPlayer.EqP[0]=jSlider1.getValue();
        CustomPlayer.EqP[1]=jSlider2.getValue();
        CustomPlayer.EqP[2]=jSlider3.getValue();
        CustomPlayer.EqP[3]=jSlider4.getValue();
        CustomPlayer.EqP[4]=jSlider5.getValue();
        CustomPlayer.EqP[5]=jSlider6.getValue();
        CustomPlayer.EqP[6]=jSlider7.getValue();
        CustomPlayer.EqP[7]=jSlider8.getValue();
        CustomPlayer.EqP[8]=jSlider9.getValue();
        CustomPlayer.EqP[9]=jSlider10.getValue();
    }
    
    private void Restablecer(){
        jSlider1.setValue(0); jSlider6.setValue(0);
        jSlider2.setValue(0); jSlider7.setValue(0);
        jSlider3.setValue(0); jSlider8.setValue(0);
        jSlider4.setValue(0); jSlider9.setValue(0);
        jSlider5.setValue(0); jSlider10.setValue(0);
    }
    private void UbicarSlider(){
        jSlider1.setValue((int)(CustomPlayer.Eq[0]*14)); jSlider6.setValue((int)(CustomPlayer.Eq[5]*14));
        jSlider2.setValue((int)(CustomPlayer.Eq[1]*14)); jSlider7.setValue((int)(CustomPlayer.Eq[6]*14));
        jSlider3.setValue((int)(CustomPlayer.Eq[2]*14)); jSlider8.setValue((int)(CustomPlayer.Eq[7]*14));
        jSlider4.setValue((int)(CustomPlayer.Eq[3]*14)); jSlider9.setValue((int)(CustomPlayer.Eq[8]*14));
        jSlider5.setValue((int)(CustomPlayer.Eq[4]*14)); jSlider10.setValue((int)(CustomPlayer.Eq[9]*14));
        jSlider11.setValue((int)(CustomPlayer.Balance*12));
    }
    
    private void GuardarInformacion(){
        Metodos.CrearCarpeta();
        ObjectOutputStream Escribir=null;
        try {
            Escribir = new ObjectOutputStream(new FileOutputStream(Metodos.Ruta()+"/Ecualizador.dat"));
            Escribir.writeFloat(CustomPlayer.Eq[0]); Escribir.writeFloat(CustomPlayer.Eq[1]);
            Escribir.writeFloat(CustomPlayer.Eq[2]); Escribir.writeFloat(CustomPlayer.Eq[3]);
            Escribir.writeFloat(CustomPlayer.Eq[4]); Escribir.writeFloat(CustomPlayer.Eq[5]);
            Escribir.writeFloat(CustomPlayer.Eq[6]); Escribir.writeFloat(CustomPlayer.Eq[7]);
            Escribir.writeFloat(CustomPlayer.Eq[8]); Escribir.writeFloat(CustomPlayer.Eq[9]);
            Escribir.writeInt(CustomPlayer.EqP[0]); Escribir.writeInt(CustomPlayer.EqP[1]);
            Escribir.writeInt(CustomPlayer.EqP[2]); Escribir.writeInt(CustomPlayer.EqP[3]);
            Escribir.writeInt(CustomPlayer.EqP[4]); Escribir.writeInt(CustomPlayer.EqP[5]);
            Escribir.writeInt(CustomPlayer.EqP[6]); Escribir.writeInt(CustomPlayer.EqP[7]);
            Escribir.writeInt(CustomPlayer.EqP[8]); Escribir.writeInt(CustomPlayer.EqP[9]);
            Escribir.writeFloat(CustomPlayer.Balance); Escribir.writeInt(CustomPlayer.ItemEc);
            Escribir.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(EqFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EqFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            Escribir=null;
        }
        
    }
    
    private void bloquearParent(){ 
        parent.setEnabled(false); 
        ((Window)parent).setFocusableWindowState(false); // Evita que el Frame padre obtenga el foco
    }
    
    private void desbloquearParent(){ 
        parent.setEnabled(true); 
        ((Window)parent).setFocusableWindowState(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider10;
    private javax.swing.JSlider jSlider11;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JSlider jSlider7;
    private javax.swing.JSlider jSlider8;
    private javax.swing.JSlider jSlider9;
    // End of variables declaration//GEN-END:variables
}
